# Generated by Django 3.0.8 on 2020-07-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vam_pais',
            fields=[
                ('id_pais', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vam_pais',
            },
        ),
    ]
