# Generated by Django 3.0.8 on 2020-07-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_pais',
            name='id_pais',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
