# Generated by Django 3.0.8 on 2020-07-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0002_auto_20200729_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='vam_asociacion_nacional',
            fields=[
                ('id_asociacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('region', models.CharField(max_length=15)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais')),
            ],
            options={
                'db_table': 'vam_asociacion_nacional',
            },
        ),
        migrations.CreateModel(
            name='vam_componente',
            fields=[
                ('id_componente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vam_componente',
            },
        ),
        migrations.CreateModel(
            name='vam_condicion_envio',
            fields=[
                ('id_condicion_envio', models.IntegerField(primary_key=True, serialize=False)),
                ('medio_transporte', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=300)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais')),
            ],
            options={
                'db_table': 'vam_condicion_envio',
            },
        ),
        migrations.CreateModel(
            name='vam_condicion_pago',
            fields=[
                ('id_condicion_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_condicion', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=300)),
                ('cuotas', models.IntegerField()),
                ('porcen_cuotas', models.IntegerField()),
                ('meses_cuotas', models.IntegerField()),
            ],
            options={
                'db_table': 'vam_condicion_pago',
            },
        ),
        migrations.CreateModel(
            name='vam_contrato',
            fields=[
                ('id_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('exclusividad', models.CharField(max_length=30)),
                ('motivo_cancelado', models.CharField(max_length=300, null=True)),
                ('fecha_cancelado', models.DateField(null=True)),
                ('quien_cancela', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'vam_contrato',
            },
        ),
        migrations.CreateModel(
            name='vam_esencia_perfume',
            fields=[
                ('id_esencia_perfume', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vam_esencia_perfume',
            },
        ),
        migrations.CreateModel(
            name='vam_familia_olfativa',
            fields=[
                ('id_familia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vam_familia_olfativa',
            },
        ),
        migrations.CreateModel(
            name='vam_ingrediente_esencia',
            fields=[
                ('id_ingrediente_esencia', models.IntegerField(primary_key=True, serialize=False)),
                ('tsca_cas_numeric', models.IntegerField()),
                ('ipc_numeric', models.IntegerField()),
                ('einecs_numeric', models.IntegerField()),
                ('descrip_proceso', models.CharField(max_length=300)),
                ('descripcion_visual', models.CharField(max_length=300)),
                ('parte_procesada', models.CharField(max_length=30)),
                ('fecha_caducidad', models.DateField()),
                ('inflamabilidad', models.IntegerField()),
                ('tipo_sustancia', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vam_ingrediente_esencia',
            },
        ),
        migrations.CreateModel(
            name='vam_ingrediente_otro',
            fields=[
                ('id_ingrediente_otro', models.IntegerField(primary_key=True, serialize=False)),
                ('tsca_cas_numeric', models.IntegerField()),
                ('ipc_numeric', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vam_ingrediente_otro',
            },
        ),
        migrations.CreateModel(
            name='vam_ingrediente_prohibido',
            fields=[
                ('id_prohibido', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vam_ingrediente_prohibido',
            },
        ),
        migrations.CreateModel(
            name='vam_intensidad',
            fields=[
                ('id_intensidad', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=3)),
                ('concentracion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vam_intensidad',
            },
        ),
        migrations.CreateModel(
            name='vam_palabra_clave',
            fields=[
                ('id_palabra', models.IntegerField(primary_key=True, serialize=False)),
                ('palabra', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'vam_palabra_clave',
            },
        ),
        migrations.CreateModel(
            name='vam_perfume',
            fields=[
                ('id_perfume', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
                ('genero', models.CharField(max_length=1)),
                ('tipo_perfume', models.CharField(max_length=10)),
                ('edad_inspiracion', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'vam_perfume',
            },
        ),
        migrations.CreateModel(
            name='vam_productor',
            fields=[
                ('id_productor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('pag_web', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('id_asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_asociacion_nacional')),
            ],
            options={
                'db_table': 'vam_productor',
            },
        ),
        migrations.CreateModel(
            name='vam_proveedor',
            fields=[
                ('id_proveedor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('pag_web', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('id_asociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_asociacion_nacional')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais')),
            ],
            options={
                'db_table': 'vam_proveedor',
            },
        ),
        migrations.CreateModel(
            name='vam_variable',
            fields=[
                ('id_variable', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vam_variable',
            },
        ),
        migrations.CreateModel(
            name='vam_telefono',
            fields=[
                ('id_telefono', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(max_length=8)),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor')),
            ],
            options={
                'db_table': 'vam_telefono',
            },
        ),
        migrations.CreateModel(
            name='vam_resultado_evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultado', models.IntegerField()),
                ('tipoeva', models.CharField(max_length=7)),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor')),
            ],
            options={
                'db_table': 'vam_resultado_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='vam_renovacion',
            fields=[
                ('id_renovacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_contrato')),
            ],
            options={
                'db_table': 'vam_renovacion',
            },
        ),
        migrations.CreateModel(
            name='vam_presentacion_perfume',
            fields=[
                ('id_presentacion_perfume', models.IntegerField(primary_key=True, serialize=False)),
                ('volumen', models.IntegerField()),
                ('id_intensidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_intensidad')),
                ('id_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume')),
            ],
            options={
                'db_table': 'vam_presentacion_perfume',
            },
        ),
        migrations.CreateModel(
            name='vam_presentacion',
            fields=[
                ('id_presentacion', models.IntegerField(primary_key=True, serialize=False)),
                ('volumen', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_ingrediente_esencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia')),
                ('id_ingrediente_otro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro')),
            ],
            options={
                'db_table': 'vam_presentacion',
            },
        ),
        migrations.CreateModel(
            name='vam_perfumista',
            fields=[
                ('id_perfumista', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=1)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais')),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
            ],
            options={
                'db_table': 'vam_perfumista',
            },
        ),
        migrations.CreateModel(
            name='vam_perf_perfumist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume')),
                ('id_perfumista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfumista')),
            ],
            options={
                'db_table': 'vam_perf_perfumist',
            },
        ),
        migrations.CreateModel(
            name='vam_pedido',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('estatus', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=10)),
                ('fecha_emision', models.DateField()),
                ('nfactura', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_condicion_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_envio')),
                ('id_condicion_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_pago')),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor')),
            ],
            options={
                'db_table': 'vam_pedido',
            },
        ),
        migrations.CreateModel(
            name='vam_pais_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor')),
            ],
            options={
                'db_table': 'vam_pais_prod',
            },
        ),
        migrations.CreateModel(
            name='vam_pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pagado', models.IntegerField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pedido')),
            ],
            options={
                'db_table': 'vam_pago',
            },
        ),
        migrations.CreateModel(
            name='vam_miembro_ifra',
            fields=[
                ('id_miembro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField()),
                ('tipo', models.CharField(max_length=8)),
                ('fecha_final', models.DateField()),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor')),
            ],
            options={
                'db_table': 'vam_miembro_ifra',
            },
        ),
        migrations.AddField(
            model_name='vam_intensidad',
            name='id_perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume'),
        ),
        migrations.AddField(
            model_name='vam_ingrediente_otro',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AddField(
            model_name='vam_ingrediente_esencia',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.CreateModel(
            name='vam_ingotro_origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingrediente_otro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais')),
            ],
            options={
                'db_table': 'vam_ingotro_origen',
            },
        ),
        migrations.CreateModel(
            name='vam_ingotro_comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_componente')),
                ('id_ingrediente_otro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro')),
            ],
            options={
                'db_table': 'vam_ingotro_comp',
            },
        ),
        migrations.CreateModel(
            name='vam_ingesen_origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingrediente_esencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais')),
            ],
            options={
                'db_table': 'vam_ingesen_origen',
            },
        ),
        migrations.CreateModel(
            name='vam_ingesen_comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_componente')),
                ('id_ingrediente_esencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia')),
            ],
            options={
                'db_table': 'vam_ingesen_comp',
            },
        ),
        migrations.CreateModel(
            name='vam_fase',
            fields=[
                ('id_fase', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_fases', models.CharField(max_length=7)),
                ('id_esencia_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_esencia_perfume')),
                ('id_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume')),
            ],
            options={
                'db_table': 'vam_fase',
            },
        ),
        migrations.CreateModel(
            name='vam_fami_perf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_olfativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa')),
                ('id_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume')),
            ],
            options={
                'db_table': 'vam_fami_perf',
            },
        ),
        migrations.CreateModel(
            name='vam_fami_palab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_olfativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa')),
                ('id_palabra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_palabra_clave')),
            ],
            options={
                'db_table': 'vam_fami_palab',
            },
        ),
        migrations.CreateModel(
            name='vam_fami_esenperf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_esencia_perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_esencia_perfume')),
                ('id_familia_olfativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa')),
            ],
            options={
                'db_table': 'vam_fami_esenperf',
            },
        ),
        migrations.CreateModel(
            name='vam_evaluacion_criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('peso', models.IntegerField()),
                ('tipopor', models.CharField(max_length=30)),
                ('fecha_fin', models.DateField()),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
                ('id_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_variable')),
            ],
            options={
                'db_table': 'vam_evaluacion_criterio',
            },
        ),
        migrations.CreateModel(
            name='vam_escala_valorada',
            fields=[
                ('id_escala', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('rango_inicio', models.IntegerField()),
                ('rango_fin', models.IntegerField()),
                ('fecha_final', models.DateField()),
                ('id_productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
            ],
            options={
                'db_table': 'vam_escala_valorada',
            },
        ),
        migrations.CreateModel(
            name='vam_elemento_contrato',
            fields=[
                ('id_elemento_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_contrato')),
                ('id_ingrediente_esencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia')),
                ('id_ingrediente_otro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro')),
            ],
            options={
                'db_table': 'vam_elemento_contrato',
            },
        ),
        migrations.CreateModel(
            name='vam_detalle_pedido',
            fields=[
                ('id_detalle', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pedido')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_presentacion_perfume')),
            ],
            options={
                'db_table': 'vam_detalle_pedido',
            },
        ),
        migrations.AddField(
            model_name='vam_contrato',
            name='id_productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AddField(
            model_name='vam_contrato',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AddField(
            model_name='vam_condicion_pago',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AddField(
            model_name='vam_condicion_envio',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.CreateModel(
            name='vam_condicion_contrato',
            fields=[
                ('id_condicion_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=300)),
                ('id_condicion_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_envio')),
                ('id_condicion_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_pago')),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_contrato')),
            ],
            options={
                'db_table': 'vam_condicion_contrato',
            },
        ),
    ]
