# Generated by Django 3.0.8 on 2020-07-29 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0003_auto_20200729_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_asociacion_nacional',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais'),
        ),
        migrations.AlterField(
            model_name='vam_condicion_contrato',
            name='id_condicion_envio',
            field=models.ForeignKey(db_column='id_condicion_envio', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_envio'),
        ),
        migrations.AlterField(
            model_name='vam_condicion_contrato',
            name='id_condicion_pago',
            field=models.ForeignKey(db_column='id_condicion_pago', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_pago'),
        ),
        migrations.AlterField(
            model_name='vam_condicion_contrato',
            name='id_contrato',
            field=models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_contrato'),
        ),
        migrations.AlterField(
            model_name='vam_condicion_envio',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais'),
        ),
        migrations.AlterField(
            model_name='vam_condicion_envio',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_condicion_pago',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_contrato',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_contrato',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_detalle_pedido',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pedido'),
        ),
        migrations.AlterField(
            model_name='vam_detalle_pedido',
            name='id_presentacion',
            field=models.ForeignKey(db_column='id_presentacion', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_presentacion_perfume'),
        ),
        migrations.AlterField(
            model_name='vam_elemento_contrato',
            name='id_contrato',
            field=models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_contrato'),
        ),
        migrations.AlterField(
            model_name='vam_elemento_contrato',
            name='id_ingrediente_esencia',
            field=models.ForeignKey(db_column='id_ingrediente_esencia', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia'),
        ),
        migrations.AlterField(
            model_name='vam_elemento_contrato',
            name='id_ingrediente_otro',
            field=models.ForeignKey(db_column='id_ingrediente_otro', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro'),
        ),
        migrations.AlterField(
            model_name='vam_escala_valorada',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_evaluacion_criterio',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_evaluacion_criterio',
            name='id_variable',
            field=models.ForeignKey(db_column='id_variable', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_variable'),
        ),
        migrations.AlterField(
            model_name='vam_fami_esenperf',
            name='id_esencia_perfume',
            field=models.ForeignKey(db_column='id_esencia_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_esencia_perfume'),
        ),
        migrations.AlterField(
            model_name='vam_fami_esenperf',
            name='id_familia_olfativa',
            field=models.ForeignKey(db_column='id_familia_olfativa', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa'),
        ),
        migrations.AlterField(
            model_name='vam_fami_palab',
            name='id_familia_olfativa',
            field=models.ForeignKey(db_column='id_familia_olfativa', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa'),
        ),
        migrations.AlterField(
            model_name='vam_fami_palab',
            name='id_palabra',
            field=models.ForeignKey(db_column='id_palabra', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_palabra_clave'),
        ),
        migrations.AlterField(
            model_name='vam_fami_perf',
            name='id_familia_olfativa',
            field=models.ForeignKey(db_column='id_familia_olfativa', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa'),
        ),
        migrations.AlterField(
            model_name='vam_fami_perf',
            name='id_perfume',
            field=models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume'),
        ),
        migrations.AlterField(
            model_name='vam_fase',
            name='id_perfume',
            field=models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume'),
        ),
        migrations.AlterField(
            model_name='vam_ingesen_comp',
            name='id_componente',
            field=models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_componente'),
        ),
        migrations.AlterField(
            model_name='vam_ingesen_comp',
            name='id_ingrediente_esencia',
            field=models.ForeignKey(db_column='id_ingrediente_esencia', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia'),
        ),
        migrations.AlterField(
            model_name='vam_ingesen_origen',
            name='id_ingrediente_esencia',
            field=models.ForeignKey(db_column='id_ingrediente_esencia', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia'),
        ),
        migrations.AlterField(
            model_name='vam_ingesen_origen',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais'),
        ),
        migrations.AlterField(
            model_name='vam_ingotro_comp',
            name='id_componente',
            field=models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_componente'),
        ),
        migrations.AlterField(
            model_name='vam_ingotro_comp',
            name='id_ingrediente_otro',
            field=models.ForeignKey(db_column='id_ingrediente', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro'),
        ),
        migrations.AlterField(
            model_name='vam_ingotro_origen',
            name='id_ingrediente_otro',
            field=models.ForeignKey(db_column='id_ingrediente_otro', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro'),
        ),
        migrations.AlterField(
            model_name='vam_ingotro_origen',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais'),
        ),
        migrations.AlterField(
            model_name='vam_ingrediente_esencia',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_ingrediente_otro',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_intensidad',
            name='id_perfume',
            field=models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume'),
        ),
        migrations.AlterField(
            model_name='vam_miembro_ifra',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_miembro_ifra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_pago',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pedido'),
        ),
        migrations.AlterField(
            model_name='vam_pais_prod',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_pais_prod',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_pedido',
            name='id_condicion_envio',
            field=models.ForeignKey(db_column='id_condicion_envio', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_envio'),
        ),
        migrations.AlterField(
            model_name='vam_pedido',
            name='id_condicion_pago',
            field=models.ForeignKey(db_column='id_condicion_pago', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_pago'),
        ),
        migrations.AlterField(
            model_name='vam_pedido',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_pedido',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_perf_perfumist',
            name='id_perfume',
            field=models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume'),
        ),
        migrations.AlterField(
            model_name='vam_perf_perfumist',
            name='id_perfumista',
            field=models.ForeignKey(db_column='id_perfumista', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfumista'),
        ),
        migrations.AlterField(
            model_name='vam_perfumista',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais'),
        ),
        migrations.AlterField(
            model_name='vam_perfumista',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_presentacion',
            name='id_ingrediente_esencia',
            field=models.ForeignKey(db_column='id_ingrediente_esencia', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia'),
        ),
        migrations.AlterField(
            model_name='vam_presentacion',
            name='id_ingrediente_otro',
            field=models.ForeignKey(db_column='id_ingrediente_otro', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro'),
        ),
        migrations.AlterField(
            model_name='vam_presentacion_perfume',
            name='id_intensidad',
            field=models.ForeignKey(db_column='id_intensidad', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_intensidad'),
        ),
        migrations.AlterField(
            model_name='vam_presentacion_perfume',
            name='id_perfume',
            field=models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume'),
        ),
        migrations.AlterField(
            model_name='vam_productor',
            name='id_asociacion',
            field=models.ForeignKey(db_column='id_asociacion', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_asociacion_nacional'),
        ),
        migrations.AlterField(
            model_name='vam_proveedor',
            name='id_asociacion',
            field=models.ForeignKey(db_column='id_asociacion', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_asociacion_nacional'),
        ),
        migrations.AlterField(
            model_name='vam_proveedor',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais'),
        ),
        migrations.AlterField(
            model_name='vam_renovacion',
            name='id_contrato',
            field=models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_contrato'),
        ),
        migrations.AlterField(
            model_name='vam_resultado_evaluacion',
            name='id_productor',
            field=models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_resultado_evaluacion',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
        migrations.AlterField(
            model_name='vam_telefono',
            name='id_productor',
            field=models.ForeignKey(db_column='productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor'),
        ),
        migrations.AlterField(
            model_name='vam_telefono',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
    ]
