# Generated by Django 3.0.8 on 2020-07-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0004_auto_20200729_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_proveedor',
            name='id_asociacion',
            field=models.ForeignKey(db_column='id_asociacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_asociacion_nacional'),
        ),
    ]
