# Generated by Django 3.0.8 on 2020-07-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0006_auto_20200729_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_miembro_ifra',
            name='tipo',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='vam_telefono',
            name='tipo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
