# Generated by Django 3.0.8 on 2020-07-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0010_auto_20200729_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_miembro_ifra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_proveedor'),
        ),
    ]
