# Generated by Django 3.0.8 on 2020-07-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0012_auto_20200729_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_telefono',
            name='numero',
            field=models.BigIntegerField(),
        ),
    ]
