# Generated by Django 3.0.8 on 2020-07-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0014_auto_20200729_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vam_pais_prod',
            name='id_proveedor',
        ),
        migrations.AddField(
            model_name='vam_pais_prod',
            name='id_pais',
            field=models.ForeignKey(db_column='id_pais', default=1, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_pais'),
        ),
    ]
