# Generated by Django 3.0.8 on 2020-07-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0015_auto_20200729_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vam_condicion_pago',
            old_name='porcen_cuotas',
            new_name='porcen_cuota',
        ),
    ]
