# Generated by Django 3.0.8 on 2020-07-29 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0021_auto_20200729_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='vam_condicion_contrato',
            name='id_pais_envio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vam_condicion_contrato',
            name='id_proveedor_envio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vam_condicion_contrato',
            name='id_proveedor_pago',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vam_condicion_contrato',
            name='id_condicion_envio',
            field=models.ForeignKey(db_column='id_condicion_envio', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_envio'),
        ),
        migrations.AlterField(
            model_name='vam_condicion_contrato',
            name='id_condicion_pago',
            field=models.ForeignKey(db_column='id_condicion_pago', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_pago'),
        ),
    ]
