# Generated by Django 3.0.8 on 2020-07-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0022_auto_20200729_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_evaluacion_criterio',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
