# Generated by Django 3.0.8 on 2020-07-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0023_auto_20200729_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='vam_ingrediente_esencia',
            name='solubilidad',
            field=models.CharField(default='fail', max_length=50),
        ),
    ]
