# Generated by Django 3.0.8 on 2020-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0024_vam_ingrediente_esencia_solubilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_ingrediente_esencia',
            name='ipc_numeric',
            field=models.IntegerField(null=True),
        ),
    ]
