# Generated by Django 3.0.8 on 2020-07-29 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0026_auto_20200729_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_ingrediente_esencia',
            name='parte_procesada',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
