# Generated by Django 3.0.8 on 2020-07-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0030_auto_20200729_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_ingrediente_esencia',
            name='einecs_numeric',
            field=models.IntegerField(null=True),
        ),
    ]
