# Generated by Django 3.0.8 on 2020-07-29 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0032_auto_20200729_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='vam_perf_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_perfume', models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume')),
                ('id_productor', models.ForeignKey(db_column='id_productor', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_productor')),
            ],
            options={
                'db_table': 'vam_perf_prod',
            },
        ),
        migrations.CreateModel(
            name='vam_perf_comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_componente', models.ForeignKey(db_column='id_componente', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_componente')),
                ('id_perfume', models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume')),
            ],
            options={
                'db_table': 'vam_perf_comp',
            },
        ),
        migrations.CreateModel(
            name='vam_monolitico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_esencia_perfume', models.ForeignKey(db_column='id_esencia_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_componente')),
                ('id_perfume', models.ForeignKey(db_column='id_perfume', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume')),
            ],
            options={
                'db_table': 'vam_monolitico',
            },
        ),
        migrations.CreateModel(
            name='vam_fami_ingotro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_olfativa', models.ForeignKey(db_column='id_familia_olfativa', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa')),
                ('id_ingrediente_otro', models.ForeignKey(db_column='id_ingrediente_otro', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia')),
            ],
            options={
                'db_table': 'vam_fami_ingotro',
            },
        ),
        migrations.CreateModel(
            name='vam_fami_ingesen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_familia_olfativa', models.ForeignKey(db_column='id_familia_olfativa', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_familia_olfativa')),
                ('id_ingrediente_esencia', models.ForeignKey(db_column='id_ingrediente_esencia', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia')),
            ],
            options={
                'db_table': 'vam_fami_ingesen',
            },
        ),
    ]
