# Generated by Django 3.0.8 on 2020-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0033_vam_fami_ingesen_vam_fami_ingotro_vam_monolitico_vam_perf_comp_vam_perf_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_perfumista',
            name='segundo_nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
