# Generated by Django 3.0.8 on 2020-07-29 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0034_auto_20200729_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='vam_pedido',
            name='id_contrato_envio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vam_pedido',
            name='id_contrato_pago',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vam_pedido',
            name='id_condicion_envio',
            field=models.ForeignKey(db_column='id_condicion_envio', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_envio'),
        ),
        migrations.AlterField(
            model_name='vam_pedido',
            name='id_condicion_pago',
            field=models.ForeignKey(db_column='id_condicion_pago', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_condicion_pago'),
        ),
        migrations.AlterField(
            model_name='vam_pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
