# Generated by Django 3.0.8 on 2020-07-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0035_auto_20200729_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_pedido',
            name='precio_total',
            field=models.FloatField(),
        ),
    ]
