# Generated by Django 3.0.8 on 2020-07-29 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0036_auto_20200729_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_elemento_contrato',
            name='id_ingrediente_esencia',
            field=models.ForeignKey(db_column='id_ingrediente_esencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_esencia'),
        ),
        migrations.AlterField(
            model_name='vam_elemento_contrato',
            name='id_ingrediente_otro',
            field=models.ForeignKey(db_column='id_ingrediente_otro', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro'),
        ),
    ]
