# Generated by Django 3.0.8 on 2020-07-29 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0037_auto_20200729_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_ingotro_comp',
            name='id_ingrediente_otro',
            field=models.ForeignKey(db_column='id_ingrediente_otro', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_ingrediente_otro'),
        ),
    ]
