# Generated by Django 3.0.8 on 2020-07-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0039_auto_20200729_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_presentacion',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vam_presentacion',
            name='volumen',
            field=models.FloatField(),
        ),
    ]
