# Generated by Django 3.0.8 on 2020-07-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0040_auto_20200729_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_detalle_pedido',
            name='subtotal',
            field=models.FloatField(),
        ),
    ]
