# Generated by Django 3.0.8 on 2020-07-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0041_auto_20200729_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_intensidad',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
