# Generated by Django 3.0.8 on 2020-07-29 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0042_auto_20200729_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_monolitico',
            name='id_perfume',
            field=models.ForeignKey(db_column='id_perfume', null=True, on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_perfume'),
        ),
    ]
