# Generated by Django 3.0.8 on 2020-07-29 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0044_auto_20200729_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vam_detalle_pedido',
            name='id_presentacion',
            field=models.ForeignKey(db_column='id_presentacion', on_delete=django.db.models.deletion.CASCADE, to='perfume.vam_presentacion'),
        ),
    ]
